//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Order_For_Digital_Printing_Of_Photos.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Format
    {
        public int formatID { get; set; }
        public string formatName { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
    }
}
