//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Order_For_Digital_Printing_Of_Photos.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public int photoID { get; set; }
        public string photoName { get; set; }
        public string description { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> cateID { get; set; }
        public string photoLink { get; set; }
        public Nullable<int> formatID { get; set; }
        public Nullable<int> Price { get; set; }
        public string ID { get; set; }
    }
}
