//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Order_For_Digital_Printing_Of_Photos.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int priceID { get; set; }
        public Nullable<int> photoFormatID { get; set; }
        public Nullable<double> price1 { get; set; }
    }
}
