//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Order_For_Digital_Printing_Of_Photos.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int userID { get; set; }
        public string userName { get; set; }
        public string userPwd { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public int status { get; set; }
        public string role { get; set; }
        public string name { get; set; }
    }
}
